In [1]:
import pandas as pd

In [2]:
%pwd

'c:\\dev\\github\\final\\Final_project'

In [3]:
%cd C:/dev/github/final/Final_project/data

C:\dev\github\final\Final_project\data

In [4]:
df = pd.read_csv('df_json.csv', encoding = "UTF-8")
df

C:\Users\유준선\AppData\Local\Temp\ipykernel_5608\4015611454.py:1: DtypeWarning: Columns (24,28,29,33,37,39,40,41,44,45,46,47) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('df_json.csv', encoding = "UTF-8")

,Unnamed: 0,file_name,width,height,imgfile,drug_N,drug_S,back_color,drug_dir,light_color,...,form_code_name,mark_code_front_anal,mark_code_back_anal,mark_code_front_img,mark_code_back_img,mark_code_front,mark_code_back,change_date,area,bbox
0,0,K-000059_0_0_0_0_60_000_200.png,976,1280,K-000059_0_0_0_0_60_000_200.png,K-000059,정상알약,검은색 배경,앞면,전구색,...,나정,NaN,NaN,NaN,NaN,NaN,NaN,20191220.0,79508,"[375, 474, 286, 278]"
1,1,K-000059_0_0_0_0_60_020_200.png,976,1280,K-000059_0_0_0_0_60_020_200.png,K-000059,정상알약,검은색 배경,앞면,전구색,...,나정,NaN,NaN,NaN,NaN,NaN,NaN,20191220.0,78668,"[382, 482, 284, 277]"
2,2,K-000059_0_0_0_0_60_040_200.png,976,1280,K-000059_0_0_0_0_60_040_200.png,K-000059,정상알약,검은색 배경,앞면,전구색,...,나정,NaN,NaN,NaN,NaN,NaN,NaN,20191220.0,79242,"[386, 491, 281, 282]"
3,3,K-000059_0_0_0_0_60_060_200.png,976,1280,K-000059_0_0_0_0_60_060_200.png,K-000059,정상알약,검은색 배경,앞면,전구색,...,나정,NaN,NaN,NaN,NaN,NaN,NaN,20191220.0,79524,"[385, 502, 282, 282]"
4,4,K-000059_0_0_0_0_60_080_200.png,976,1280,K-000059_0_0_0_0_60_080_200.png,K-000059,정상알약,검은색 배경,앞면,전구색,...,나정,NaN,NaN,NaN,NaN,NaN,NaN,20191220.0,79520,"[378, 512, 284, 280]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2451922,2451922,K-039147_0_2_1_2_90_260_200.png,976,1280,K-039147_0_2_1_2_90_260_200.png,K-039147,정상알약,연회색 배경,뒷면,주백색,...,필름코팅정,NaN,NaN,NaN,NaN,NaN,NaN,20200916.0,33660,"[395, 546, 187, 180]"
2451923,2451923,K-039147_0_2_1_2_90_280_200.png,976,1280,K-039147_0_2_1_2_90_280_200.png,K-039147,정상알약,연회색 배경,뒷면,주백색,...,필름코팅정,NaN,NaN,NaN,NaN,NaN,NaN,20200916.0,33480,"[395, 547, 186, 180]"
2451924,2451924,K-039147_0_2_1_2_90_300_200.png,976,1280,K-039147_0_2_1_2_90_300_200.png,K-039147,정상알약,연회색 배경,뒷면,주백색,...,필름코팅정,NaN,NaN,NaN,NaN,NaN,NaN,20200916.0,31313,"[396, 556, 181, 173]"
2451925,2451925,K-039147_0_2_1_2_90_320_200.png,976,1280,K-039147_0_2_1_2_90_320_200.png,K-039147,정상알약,연회색 배경,뒷면,주백색,...,필름코팅정,NaN,NaN,NaN,NaN,NaN,NaN,20200916.0,29392,"[405, 554, 176, 167]"
2451926,2451926,K-039147_0_2_1_2_90_340_200.png,976,1280,K-039147_0_2_1_2_90_340_200.png,K-039147,정상알약,연회색 배경,뒷면,주백색,...,필름코팅정,NaN,NaN,NaN,NaN,NaN,NaN,20200916.0,31494,"[405, 554, 181, 174]"

In [5]:
df.drop('Unnamed: 0', axis = 1, inplace = True)
df.shape

(2451927, 52)

In [23]:
df2 = df.copy()

In [24]:
df2.isna().sum()

file_name                     0
width                         0
height                        0
imgfile                       0
drug_N                        0
drug_S                        0
back_color                    0
drug_dir                      0
light_color                   0
camera_la                     0
camera_lo                     0
size                          0
item_seq                      0
leng_long                 14256
leng_short                14688
thick                     14472
id                            0
dl_idx                        0
dl_mapping_code               0
dl_name                       0
dl_name_en                30456
img_key                   30240
dl_material               10692
dl_material_en           174204
dl_custom_shape           75816
dl_company                    0
dl_company_en               216
di_company_mf           1731454
di_company_mf_en        1948966
di_item_permit_date           0
di_class_no                2592
di_etc_otc_code               0
di_edi_code               57240
chart                     30240
drug_shape                30240
print_front               64692
print_back              1203442
color_class1              30240
color_class2            2154819
line_front              2120367
line_back               2043898
img_regist_ts             30240
form_code_name            30240
mark_code_front_anal    2156871
mark_code_back_anal     2353431
mark_code_front_img     2154279
mark_code_back_img      2352135
mark_code_front         2451927
mark_code_back          2451927
change_date              148722
area                          0
bbox                          0
dtype: int64

In [25]:
df2.id.value_counts()  # 모두 1로 같아서 제거함

id
1    2451927
Name: count, dtype: int64

In [26]:
df2.dl_custom_shape.value_counts()

dl_custom_shape
정제, 저작정                1766991
경질캡슐제                   222264
서방형정제                   155520
장용정제                     80352
연질캡슐제                    74196
확산정, 속붕정, 구강붕해정          28296
서방캡슐제                    24948
장용캡슐제                    10368
설하정                       6912
트로키제                      4104
환제                        1296
현탁제, 현탁액용정제, 현탁액용산제        648
과립제, 세립                    216
Name: count, dtype: int64

In [10]:
df2.di_class_no.value_counts()

di_class_no
[01140]해열.진통.소염제    303702
[02140]혈압강하제        227448
[02190]기타의 순환계용약    161460
[02180]동맥경화용제       122795
[01170]정신신경용제       118692
                     ...
[03320]지혈제             324
[06230]치나제             324
[02460]남성호르몬제          324
[02560]치질용제            216
[02690]기타의 외피용약        216
Name: count, Length: 87, dtype: int64

# 열 삭제

In [27]:
df2.drop(['id', 'dl_company_en', 'di_company_mf', 'di_company_mf_en',
          'mark_code_front', 'mark_code_back'], axis = 1, inplace = True)
df2

,file_name,width,height,imgfile,drug_N,drug_S,back_color,drug_dir,light_color,camera_la,...,line_back,img_regist_ts,form_code_name,mark_code_front_anal,mark_code_back_anal,mark_code_front_img,mark_code_back_img,change_date,area,bbox
0,K-000059_0_0_0_0_60_000_200.png,976,1280,K-000059_0_0_0_0_60_000_200.png,K-000059,정상알약,검은색 배경,앞면,전구색,60,...,NaN,20041222.0,나정,NaN,NaN,NaN,NaN,20191220.0,79508,"[375, 474, 286, 278]"
1,K-000059_0_0_0_0_60_020_200.png,976,1280,K-000059_0_0_0_0_60_020_200.png,K-000059,정상알약,검은색 배경,앞면,전구색,60,...,NaN,20041222.0,나정,NaN,NaN,NaN,NaN,20191220.0,78668,"[382, 482, 284, 277]"
2,K-000059_0_0_0_0_60_040_200.png,976,1280,K-000059_0_0_0_0_60_040_200.png,K-000059,정상알약,검은색 배경,앞면,전구색,60,...,NaN,20041222.0,나정,NaN,NaN,NaN,NaN,20191220.0,79242,"[386, 491, 281, 282]"
3,K-000059_0_0_0_0_60_060_200.png,976,1280,K-000059_0_0_0_0_60_060_200.png,K-000059,정상알약,검은색 배경,앞면,전구색,60,...,NaN,20041222.0,나정,NaN,NaN,NaN,NaN,20191220.0,79524,"[385, 502, 282, 282]"
4,K-000059_0_0_0_0_60_080_200.png,976,1280,K-000059_0_0_0_0_60_080_200.png,K-000059,정상알약,검은색 배경,앞면,전구색,60,...,NaN,20041222.0,나정,NaN,NaN,NaN,NaN,20191220.0,79520,"[378, 512, 284, 280]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2451922,K-039147_0_2_1_2_90_260_200.png,976,1280,K-039147_0_2_1_2_90_260_200.png,K-039147,정상알약,연회색 배경,뒷면,주백색,90,...,NaN,20160725.0,필름코팅정,NaN,NaN,NaN,NaN,20200916.0,33660,"[395, 546, 187, 180]"
2451923,K-039147_0_2_1_2_90_280_200.png,976,1280,K-039147_0_2_1_2_90_280_200.png,K-039147,정상알약,연회색 배경,뒷면,주백색,90,...,NaN,20160725.0,필름코팅정,NaN,NaN,NaN,NaN,20200916.0,33480,"[395, 547, 186, 180]"
2451924,K-039147_0_2_1_2_90_300_200.png,976,1280,K-039147_0_2_1_2_90_300_200.png,K-039147,정상알약,연회색 배경,뒷면,주백색,90,...,NaN,20160725.0,필름코팅정,NaN,NaN,NaN,NaN,20200916.0,31313,"[396, 556, 181, 173]"
2451925,K-039147_0_2_1_2_90_320_200.png,976,1280,K-039147_0_2_1_2_90_320_200.png,K-039147,정상알약,연회색 배경,뒷면,주백색,90,...,NaN,20160725.0,필름코팅정,NaN,NaN,NaN,NaN,20200916.0,29392,"[405, 554, 176, 167]"
2451926,K-039147_0_2_1_2_90_340_200.png,976,1280,K-039147_0_2_1_2_90_340_200.png,K-039147,정상알약,연회색 배경,뒷면,주백색,90,...,NaN,20160725.0,필름코팅정,NaN,NaN,NaN,NaN,20200916.0,31494,"[405, 554, 181, 174]"

In [28]:
df2['di_class_no'].fillna('unknown', inplace = True)
df2.di_class_no.isna().sum()

0

In [29]:
df2['dl_name_en'].fillna('unknown', inplace = True)
df2.dl_name_en.isna().sum()

0

In [30]:
df2['img_key'].fillna('unknown', inplace = True)
df2.img_key.isna().sum()

0

In [31]:
df2['dl_material'].fillna('unknown', inplace = True)
df2.dl_material.isna().sum()

0

In [32]:
df2['dl_material_en'].fillna('unknown', inplace = True)
df2.dl_material_en.isna().sum()

0

In [33]:
df2['leng_long'].fillna(0, inplace = True)
df2.leng_long.isna().sum()

0

In [34]:
df2['leng_short'].fillna(0, inplace = True)
df2.leng_short.isna().sum()

0

In [35]:
df2['thick'].fillna(0, inplace = True)
df2.dl_material_en.isna().sum()

0

In [ ]:
# id(약제 이미지식별자) -> 1로 모두 동일 -> 유의미한 값이 들어있는 열이 아니므로 제거해도 되지 않을까?
# dl_company(제조사명) -> 결측값 없음. 이 열만 활용한다면 제조사명(영어), 위탁 제조사명(한글/영어)은 불필요하지 않을까?
# 알약 길이 관련(장축(leng_long), 단축(leng_short), 두께(thick)) -> 0으로 fill
# di_class_no(약품분류), 약 영어이름(dl_name_en), 이미지 링크(img_key), 성분명(dl_material), 영어 성분명(dl_material_en) -> unknown

# 중간 점검

In [36]:
df2.isna().sum()

file_name                     0
width                         0
height                        0
imgfile                       0
drug_N                        0
drug_S                        0
back_color                    0
drug_dir                      0
light_color                   0
camera_la                     0
camera_lo                     0
size                          0
item_seq                      0
leng_long                     0
leng_short                    0
thick                         0
dl_idx                        0
dl_mapping_code               0
dl_name                       0
dl_name_en                    0
img_key                       0
dl_material                   0
dl_material_en                0
dl_custom_shape           75816
dl_company                    0
di_item_permit_date           0
di_class_no                   0
di_etc_otc_code               0
di_edi_code               57240
chart                     30240
drug_shape                30240
print_front               64692
print_back              1203442
color_class1              30240
color_class2            2154819
line_front              2120367
line_back               2043898
img_regist_ts             30240
form_code_name            30240
mark_code_front_anal    2156871
mark_code_back_anal     2353431
mark_code_front_img     2154279
mark_code_back_img      2352135
change_date              148722
area                          0
bbox                          0
dtype: int64

In [67]:
df2.form_code_name.value_counts()

form_code_name
필름코팅정              1162725
나정                  542814
경질캡슐제, 산제           217080
서방성필름코팅정            108648
장용성필름코팅정             90504
연질캡슐제, 액상            39204
당의정                  38772
연질캡슐제, 현탁상           36936
추어블정(저작정)            29592
구강붕해정                26568
서방정                  25920
서방성캡슐제, 펠렛           23652
다층정                  22032
경질캡슐제, 과립제           16200
설하정                   6912
장용성당의정                6372
트로키제                  5400
장용성캡슐제, 펠렛            4212
경질캡슐제, 서방성장용성펠렛       3240
발포정                   2808
장용성캡슐제, 정제            1944
경질캡슐제, 과립제정제          1620
경질캡슐제, 장용성과립제         1620
서방성다층정                1512
서방성장용필름코팅정            1512
경질캡슐제, 정제             1296
장용성필름코팅캡슐제            1296
분산정(현탁정)               432
스팬슐                    324
산제                     324
장용정                    216
Name: count, dtype: int64

In [ ]:
# dl_custom_shape, di_edi_code, chart, drug_shape, form_code_name -> unknown
# color_class_2(색상2)는 color_class_1만 있으니 지워도 ㄱㅊ을듯
# img_regist_ts(약학정보원 이미지 생성일) -> 불필요한 정보
# print_front, print_back, line_front, line_back -> 일단 보류
# mark_code(마크이미지) 관련 -> 일단 보류
  # 데이터가 너무 적음 (결측치 200만개 초과) -> 유의미한 정보가 될 수 있을까..?

In [69]:
df2.drop(['color_class2', 'img_regist_ts'], axis = 1, inplace = True)
df2.isna().sum()

file_name                     0
width                         0
height                        0
imgfile                       0
drug_N                        0
drug_S                        0
back_color                    0
drug_dir                      0
light_color                   0
camera_la                     0
camera_lo                     0
size                          0
item_seq                      0
leng_long                     0
leng_short                    0
thick                         0
dl_idx                        0
dl_mapping_code               0
dl_name                       0
dl_name_en                    0
img_key                       0
dl_material                   0
dl_material_en                0
dl_custom_shape           75816
dl_company                    0
di_item_permit_date           0
di_class_no                   0
di_etc_otc_code               0
di_edi_code               57240
chart                     30240
drug_shape                30240
print_front               64692
print_back              1203442
color_class1              30240
line_front              2120367
line_back               2043898
form_code_name            30240
mark_code_front_anal    2156871
mark_code_back_anal     2353431
mark_code_front_img     2154279
mark_code_back_img      2352135
change_date              148722
area                          0
bbox                          0
dtype: int64

In [70]:
df2['dl_custom_shape'].fillna('unknown', inplace = True)
df2.dl_custom_shape.isna().sum()

0

In [71]:
df2['di_edi_code'].fillna('unknown', inplace = True)
df2.di_edi_code.isna().sum()

0

In [72]:
df2['chart'].fillna('unknown', inplace = True)
df2.chart.isna().sum()

0

In [73]:
df2['drug_shape'].fillna('unknown', inplace = True)
df2.drug_shape.isna().sum()

0

In [74]:
df2['form_code_name'].fillna('unknown', inplace = True)
df2.form_code_name.isna().sum()

0

In [75]:
df2.isna().sum()

file_name                     0
width                         0
height                        0
imgfile                       0
drug_N                        0
drug_S                        0
back_color                    0
drug_dir                      0
light_color                   0
camera_la                     0
camera_lo                     0
size                          0
item_seq                      0
leng_long                     0
leng_short                    0
thick                         0
dl_idx                        0
dl_mapping_code               0
dl_name                       0
dl_name_en                    0
img_key                       0
dl_material                   0
dl_material_en                0
dl_custom_shape               0
dl_company                    0
di_item_permit_date           0
di_class_no                   0
di_etc_otc_code               0
di_edi_code                   0
chart                         0
drug_shape                    0
print_front               64692
print_back              1203442
color_class1              30240
line_front              2120367
line_back               2043898
form_code_name                0
mark_code_front_anal    2156871
mark_code_back_anal     2353431
mark_code_front_img     2154279
mark_code_back_img      2352135
change_date              148722
area                          0
bbox                          0
dtype: int64

In [76]:
%pwd

'C:\\dev\\github\\final\\Final_project\\data'

In [77]:
df2.to_csv('df_processing.csv')

In [41]:
df_letter = df2[['print_front', 'print_back']]
df_letter

        print_front print_back
0                 G          G
1                 G          G
2                 G          G
3                 G          G
4                 G          G
...             ...        ...
2451922         A31        F31
2451923         A31        F31
2451924         A31        F31
2451925         A31        F31
2451926         A31        F31

[2451927 rows x 2 columns]

In [60]:
df_letter.iloc[3]

print_front    G
print_back     G
Name: 3, dtype: object

In [58]:
lst = []
for i in range(len(df_letter)):
    if int(df_letter.iloc[i, :].isna().sum()) == 0:
        pass
    else:
        lst.append(df_letter.iloc[i])

lst

[print_front    마크분할선ST
 print_back         NaN
 Name: 5184, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5185, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5186, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5187, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5188, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5189, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5190, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5191, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5192, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5193, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5194, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5195, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5196, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5197, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5198, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5199, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5200, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5201, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5202, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5203, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5204, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5205, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5206, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5207, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5208, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5209, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5210, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5211, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5212, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5213, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5214, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5215, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5216, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5217, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5218, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5219, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5220, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5221, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5222, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5223, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5224, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5225, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5226, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5227, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5228, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5229, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5230, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5231, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5232, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5233, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5234, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5235, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5236, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5237, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5238, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5239, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5240, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5241, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5242, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5243, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5244, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5245, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5246, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5247, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5248, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5249, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5250, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5251, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5252, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5253, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5254, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5255, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5256, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5257, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5258, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5259, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5260, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5261, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5262, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5263, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5264, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5265, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5266, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5267, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5268, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5269, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5270, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5271, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5272, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5273, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5274, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5275, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5276, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5277, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5278, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5279, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5280, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5281, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5282, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5283, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5284, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5285, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5286, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5287, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5288, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5289, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5290, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5291, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5292, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5293, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5294, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5295, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5296, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5297, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5298, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5299, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5300, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5301, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5302, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5303, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5304, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5305, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5306, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5307, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5308, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5309, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5310, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5311, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5312, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5313, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5314, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5315, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5316, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5317, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5318, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5319, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5320, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5321, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5322, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5323, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5324, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5325, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5326, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5327, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5328, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5329, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5330, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5331, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5332, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5333, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5334, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5335, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5336, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5337, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5338, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5339, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5340, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5341, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5342, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5343, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5344, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5345, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5346, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5347, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5348, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5349, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5350, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5351, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5352, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5353, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5354, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5355, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5356, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5357, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5358, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5359, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5360, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5361, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5362, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5363, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5364, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5365, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5366, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5367, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5368, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5369, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5370, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5371, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5372, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5373, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5374, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5375, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5376, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5377, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5378, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5379, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5380, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5381, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5382, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5383, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5384, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5385, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5386, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5387, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5388, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5389, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5390, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5391, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5392, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5393, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5394, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5395, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5396, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5397, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5398, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5399, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5400, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5401, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5402, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5403, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5404, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5405, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5406, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5407, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5408, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5409, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5410, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5411, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5412, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5413, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5414, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5415, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5416, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5417, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5418, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5419, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5420, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5421, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5422, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5423, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5424, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5425, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5426, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5427, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5428, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5429, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5430, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5431, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5432, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5433, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5434, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5435, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5436, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5437, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5438, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5439, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5440, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5441, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5442, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5443, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5444, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5445, dtype: object,
 print_front    마크분할선ST
 print_back         NaN
 Name: 5446, dtype: object,

In [59]:
len(lst)

1212838

In [ ]:
# dl_custom_shape(제조 모양), di_edi_code(EDI 코드), chart(알약 제형), drug_shape(알약 모양)

In [37]:
df2.dl_custom_shape.value_counts()

dl_custom_shape
정제, 저작정                1766991
경질캡슐제                   222264
서방형정제                   155520
장용정제                     80352
연질캡슐제                    74196
확산정, 속붕정, 구강붕해정          28296
서방캡슐제                    24948
장용캡슐제                    10368
설하정                       6912
트로키제                      4104
환제                        1296
현탁제, 현탁액용정제, 현탁액용산제        648
과립제, 세립                    216
Name: count, dtype: int64

In [29]:
df.drop(['Unnamed: 0', 'mark_code_front_anal', 'mark_code_back_anal', 'mark_code_front_img', 'mark_code_back_img',
         'mark_code_front', 'mark_code_back', 'change_date'], axis = 1, inplace = True)
df.head()

,file_name,width,height,imgfile,drug_N,drug_S,back_color,drug_dir,light_color,camera_la,...,print_front,print_back,color_class1,color_class2,line_front,line_back,img_regist_ts,form_code_name,area,bbox
0,K-000059_0_0_0_0_60_000_200.png,976,1280,K-000059_0_0_0_0_60_000_200.png,K-000059,정상알약,검은색 배경,앞면,전구색,60,...,G,G,하양,NaN,NaN,NaN,20041222.0,나정,79508,"[375, 474, 286, 278]"
1,K-000059_0_0_0_0_60_020_200.png,976,1280,K-000059_0_0_0_0_60_020_200.png,K-000059,정상알약,검은색 배경,앞면,전구색,60,...,G,G,하양,NaN,NaN,NaN,20041222.0,나정,78668,"[382, 482, 284, 277]"
2,K-000059_0_0_0_0_60_040_200.png,976,1280,K-000059_0_0_0_0_60_040_200.png,K-000059,정상알약,검은색 배경,앞면,전구색,60,...,G,G,하양,NaN,NaN,NaN,20041222.0,나정,79242,"[386, 491, 281, 282]"
3,K-000059_0_0_0_0_60_060_200.png,976,1280,K-000059_0_0_0_0_60_060_200.png,K-000059,정상알약,검은색 배경,앞면,전구색,60,...,G,G,하양,NaN,NaN,NaN,20041222.0,나정,79524,"[385, 502, 282, 282]"
4,K-000059_0_0_0_0_60_080_200.png,976,1280,K-000059_0_0_0_0_60_080_200.png,K-000059,정상알약,검은색 배경,앞면,전구색,60,...,G,G,하양,NaN,NaN,NaN,20041222.0,나정,79520,"[378, 512, 284, 280]"

In [30]:
df.isna().sum()

file_name                    0
width                        0
height                       0
imgfile                      0
drug_N                       0
drug_S                       0
back_color                   0
drug_dir                     0
light_color                  0
camera_la                    0
camera_lo                    0
size                         0
item_seq                     0
leng_long                14256
leng_short               14688
thick                    14472
id                           0
dl_idx                       0
dl_mapping_code              0
dl_name                      0
dl_name_en               30456
img_key                  30240
dl_material              10692
dl_material_en          174204
dl_custom_shape          75816
dl_company                   0
dl_company_en              216
di_company_mf          1731454
di_company_mf_en       1948966
di_item_permit_date          0
di_class_no               2592
di_etc_otc_code              0
di_edi_code              57240
chart                    30240
drug_shape               30240
print_front              64692
print_back             1203442
color_class1             30240
color_class2           2154819
line_front             2120367
line_back              2043898
img_regist_ts            30240
form_code_name           30240
area                         0
bbox                         0
dtype: int64

In [33]:
df['dl_material'].isna()

0          True
1          True
2          True
3          True
4          True
           ...
2451922    True
2451923    True
2451924    True
2451925    True
2451926    True
Name: dl_material, Length: 2451927, dtype: bool

In [13]:
df.line_back.value_counts()  # -, +, 기타 => line_front와 마찬가지

line_back
-     383405
+      22032
기타      2592
Name: count, dtype: int64

In [15]:
df.color_class1.value_counts()

color_class1
하양        1010556
노랑         327024
분홍         292788
주황         179819
연두         130678
갈색         126036
파랑         122586
초록          87372
빨강          46872
회색          18576
보라          13608
청록          11124
노랑, 투명       9396
초록, 투명       5832
검정           5724
하양, 노랑       5400
파랑, 투명       4536
주황, 투명       3888
자주           3564
빨강, 투명       3564
청록, 투명       2916
갈색, 투명       2268
남색           1944
하양, 갈색       1512
하양, 빨강       1296
하양, 투명        648
투명            648
보라, 투명        648
분홍, 투명        648
하양, 파랑        216
Name: count, dtype: int64

In [14]:
df.color_class2.value_counts()

color_class2
하양        108756
노랑         82080
파랑         26028
갈색         12312
주황         11664
초록         10692
빨강          9072
분홍          8316
연두          7128
투명          3888
파랑, 옅은      2916
회색          2916
하양, 투명      1944
보라          1620
주황, 투명      1296
자주          1296
노랑, 옅은       972
검정           648
갈색, 진한       648
노랑, 진한       324
초록, 진한       324
청록, 옅은       324
연두, 진한       324
남색           324
초록, 옅은       324
분홍, 투명       324
청록           324
갈색, 투명       324
Name: count, dtype: int64

In [22]:
df[df['dl_name_en'].isnull()]

,file_name,width,height,imgfile,drug_N,drug_S,back_color,drug_dir,light_color,camera_la,...,line_back,img_regist_ts,form_code_name,mark_code_front_anal,mark_code_back_anal,mark_code_front_img,mark_code_back_img,change_date,area,bbox
753624,K-026561_0_0_0_0_60_000_200.png,976,1280,K-026561_0_0_0_0_60_000_200.png,K-026561,정상알약,검은색 배경,앞면,전구색,60,...,-,20200625.0,추어블정(저작정),NaN,NaN,NaN,NaN,20200408.0,86376,"[303, 476, 354, 244]"
753625,K-026561_0_0_0_0_60_020_200.png,976,1280,K-026561_0_0_0_0_60_020_200.png,K-026561,정상알약,검은색 배경,앞면,전구색,60,...,-,20200625.0,추어블정(저작정),NaN,NaN,NaN,NaN,20200408.0,94734,"[317, 463, 342, 277]"
753626,K-026561_0_0_0_0_60_040_200.png,976,1280,K-026561_0_0_0_0_60_040_200.png,K-026561,정상알약,검은색 배경,앞면,전구색,60,...,-,20200625.0,추어블정(저작정),NaN,NaN,NaN,NaN,20200408.0,101115,"[327, 449, 321, 315]"
753627,K-026561_0_0_0_0_60_060_200.png,976,1280,K-026561_0_0_0_0_60_060_200.png,K-026561,정상알약,검은색 배경,앞면,전구색,60,...,-,20200625.0,추어블정(저작정),NaN,NaN,NaN,NaN,20200408.0,100499,"[342, 442, 293, 343]"
753628,K-026561_0_0_0_0_60_080_200.png,976,1280,K-026561_0_0_0_0_60_080_200.png,K-026561,정상알약,검은색 배경,앞면,전구색,60,...,-,20200625.0,추어블정(저작정),NaN,NaN,NaN,NaN,20200408.0,87822,"[366, 435, 246, 357]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2443390,K-038910_0_0_1_2_90_260_200.png,976,1280,K-038910_0_0_1_2_90_260_200.png,K-038910,정상알약,검은색 배경,뒷면,주백색,90,...,NaN,20180306.0,"경질캡슐제, 산제",NaN,NaN,NaN,NaN,20180108.0,127602,"[386, 423, 278, 459]"
2443391,K-038910_0_0_1_2_90_280_200.png,976,1280,K-038910_0_0_1_2_90_280_200.png,K-038910,정상알약,검은색 배경,뒷면,주백색,90,...,NaN,20180306.0,"경질캡슐제, 산제",NaN,NaN,NaN,NaN,20180108.0,152184,"[333, 460, 373, 408]"
2443392,K-038910_0_0_1_2_90_300_200.png,976,1280,K-038910_0_0_1_2_90_300_200.png,K-038910,정상알약,검은색 배경,뒷면,주백색,90,...,NaN,20180306.0,"경질캡슐제, 산제",NaN,NaN,NaN,NaN,20180108.0,139635,"[300, 502, 435, 321]"
2443393,K-038910_0_0_1_2_90_320_200.png,976,1280,K-038910_0_0_1_2_90_320_200.png,K-038910,정상알약,검은색 배경,뒷면,주백색,90,...,NaN,20180306.0,"경질캡슐제, 산제",NaN,NaN,NaN,NaN,20180108.0,104901,"[274, 550, 479, 219]"
2443394,K-038910_0_0_1_2_90_340_200.png,976,1280,K-038910_0_0_1_2_90_340_200.png,K-038910,정상알약,검은색 배경,뒷면,주백색,90,...,NaN,20180306.0,"경질캡슐제, 산제",NaN,NaN,NaN,NaN,20180108.0,97812,"[268, 553, 468, 209]"

In [24]:
df.mark_code_front_anal.dropna()

5184        siL,5iL
5185        siL,5iL
5186        siL,5iL
5187        siL,5iL
5188        siL,5iL
             ...
2447386    마름모,꽃잎,원
2447387    마름모,꽃잎,원
2447388    마름모,꽃잎,원
2447389    마름모,꽃잎,원
2447390    마름모,꽃잎,원
Name: mark_code_front_anal, Length: 295056, dtype: object

In [25]:
df.mark_code_back_anal.dropna()

10368         왕관
10369         왕관
10370         왕관
10371         왕관
10372         왕관
           ...
2442742    dk,ck
2442743    dk,ck
2442744    dk,ck
2442745    dk,ck
2442746    dk,ck
Name: mark_code_back_anal, Length: 98496, dtype: object